name: Create Android production build

on:
  workflow_dispatch:
  push:
    tags:
      - mobile-v*

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
