export const EDITABLE_REVIEW_ATTEMPT_WINDOW_SIZE = 5;
export const FOCUS_SESSION_INACTIVITY_TIMEOUT_MS = 5 * 60 * 1000;
export const DETAILED_REVIEW_HISTORY_RETENTION = 100;
export const AGGREGATION_CHECK_INTERVAL = 25;
export const AGGREGATION_CHUNK_SIZE = 25;
export const FOREGROUND_AGGREGATION_CHUNK_LIMIT = 2;
export const PENDING_COMPLETED_SESSION_RECOVERY_LIMIT = 2;
