export const EDITABLE_REVIEW_ATTEMPT_WINDOW_SIZE = 5;
export const FOCUS_SESSION_INACTIVITY_TIMEOUT_MS = 5 * 60 * 1000;
export const DETAILED_REVIEW_HISTORY_RETENTION = 100;
export const COMPACTION_CHECK_INTERVAL = 25;
